name: "futbolismo"
title: "Fútbolismo - Storie e grafici del calcio"
description: "Storie e grafici del calcio"
long_description: "È un progetto nato dalla passione per il calcio raccontato attraverso storie, fatti e grafici. È un ritorno romantico al calcio dell'infanzia con una lettura più matura e critica dei personaggi e degli avvenimenti politici, culturali e storici."
url: https://futbolismo.it
wikipedia_lang: it

excerpt_separator: <!--more-->

markdown: kramdown
permalink: /:title

highlighter: rouge
encoding: utf-8

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
# baseurl: "/blog"

# Set the Sass partials directory, as we're using @imports
sass:
   sass_dir: _scss
   style: :compressed # You might prefer to minify using :compressed


# Handling Reading
safe                : false
include             : [".htaccess"]
exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

defaults:
  - scope:
      path: "assets/pics/stickers"
    values:
      sticker: true
